version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/hunterxhunter/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/data/hunterxhunter/redis:/data
  hunterxhunter:
    image: hungtpplay/hunterxhunter:local
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_DNS="host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8000
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]
    ports:
      - 8000:8000